monitor=,preferred,auto,1
exec-once = waybar &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = nm-applet &
exec-once = wireplumber
exec-once = pipewire
bind = SUPER, Return, exec, kitty
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, F, fullscreen,
bind = SUPER, Space, exec, wofi --show drun
